import mod from "@/lib/deliverables/perfil-integral.ts";
import bs from "@/lib/consultant/blindspot-map.ts";
import fs from "fs";
const buildPerfilIntegral = (mod as any).buildPerfilIntegral;
const buildBlindspotMap = (bs as any).buildBlindspotMap;
const owl = fs.readFileSync(process.cwd()+"/public/owl.png");
const competencies = { EL:108, RP:109, ACT:124, NE:98, IM:114, OP:107, EMP:105, NG:118 };
const talents = { criticalthinking:115, vision:113, prioritizing:113, reflecting:111, problemsolving:110, designing:108, entrepreneurship:107, adaptability:106, datamining:105, modeling:105, commitment:104, resilience:104, emotionalinsight:103, connection:103, proactivity:102, collaboration:99, imagination:97, risktolerance:96 };
const pulses = { MOTIVATION_MEANING:3.75, MOTIVATION_MASTERY:4.0, MOTIVATION_AUTONOMY:4.0, CHANGE_IMAGINATION:4.0, CHANGE_EXPLORATION:3.33, CHANGE_CELEBRATION:3.0, TEAMWORK_DIVERGENCE:4.0, TEAMWORK_CONNECTION:4.33, TEAMWORK_JOY:4.5, EXECUTION_FOCUS:4.0, EXECUTION_ACCOUNTABILITY:4.5, EXECUTION_FEEDBACK:4.5, TRUST_TRANSPARENCY:4.5, TRUST_COHERENCE:4.0, TRUST_CARE:4.0 };
const blindspotMap = buildBlindspotMap({ competencies, talents, pulses });
const data = { subjectLabel:"Carolina Navarro", meta:"Perfil integral SEI + LVS · Consultant · CO · 60 años · SEI 2026-04-06 · LVS Self 2026", eqTotal:110.1, kcg:{K:108.5,C:110.8,G:111.5}, competencies, talents, brainAgility:110.2, outcomes:{Effectiveness:116,Relationship:112,"Quality of Life":105,Wellbeing:106,"Overall 4 Outcome":110}, subOutcomes:{Influence:111,"Decision Making":120,Community:108,Network:116,Achievement:102,Satisfaction:109,Balance:114,Health:98}, brainStyles:{RATIONAL:108,EMOTIONAL:102,EVALUATIVE:110,INNOVATIVE:99,PRACTICAL:105,IDEALISTIC:109}, pulses, pulseScale:"lvs", drivers:[{code:"MOTIVATION",rowi:3.92,official:4.17},{code:"TEAMWORK",rowi:4.28,official:4.50},{code:"EXECUTION",rowi:4.33,official:4.25},{code:"CHANGE",rowi:3.44,official:3.70},{code:"TRUST",rowi:4.17,official:4.20}], blindspotMap, diagnosis:"“Soy fuerte donde creo serlo (Ejecución respaldada por ACT=124; Motivación por NG=118), honesta donde soy débil (Cambio, y sé que mi imaginación/riesgo son bajos) — pero tengo un punto ciego: me creo más conectada, alegre e imaginativa de lo que mi capacidad sostiene. Y subvaloro mi propósito y mi capacidad de celebrar.”", vsValidationNote:"Mapa Rowi validado contra el PDF oficial Six Seconds: error medio 0.17 pts." };
for (const lang of ["es","en","pt"]) { const buf = await buildPerfilIntegral(data, lang, owl); fs.writeFileSync(`/tmp/perfil-carolina-${lang}.pdf`, buf); console.log("OK", lang, buf.length); }
